name: pottery_frontend
version: 1.1.0+2
description: Flutter frontend for the pottery inventory application.
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  dio: ^5.4.3+1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  image_picker: ^1.1.1
  collection: ^1.18.0
  http_parser: ^4.0.2
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  # Firebase dependencies - Updated for compatibility
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/stages.json
