// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9_T4dzS6pdBL5QLB6Q4X3SDr7_tH0eg0',
    appId: '1:1073709451179:web:92276550af84ff06feb4ee',
    messagingSenderId: '1073709451179',
    projectId: 'pottery-app-456522',
    authDomain: 'pottery-app-456522.firebaseapp.com',
    storageBucket: 'pottery-app-456522.firebasestorage.app',
    measurementId: 'G-7Y02GN2Q86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBdbgkweVL7JMwZotWf2s-wYEz3paYHJk',
    appId: '1:1073709451179:android:3e9ecd43ceafa460feb4ee',
    messagingSenderId: '1073709451179',
    projectId: 'pottery-app-456522',
    storageBucket: 'pottery-app-456522.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOgCweIIq9qmQdOpPLE5EytPX-vI4-A5U',
    appId: '1:1073709451179:ios:1fc124ee9fee8cecfeb4ee',
    messagingSenderId: '1073709451179',
    projectId: 'pottery-app-456522',
    storageBucket: 'pottery-app-456522.firebasestorage.app',
    iosBundleId: 'com.example.potteryFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOgCweIIq9qmQdOpPLE5EytPX-vI4-A5U',
    appId: '1:1073709451179:ios:1fc124ee9fee8cecfeb4ee',
    messagingSenderId: '1073709451179',
    projectId: 'pottery-app-456522',
    storageBucket: 'pottery-app-456522.firebasestorage.app',
    iosBundleId: 'com.example.potteryFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your-web-api-key',
    appId: 'your-web-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    authDomain: 'your-project-id.firebaseapp.com',
    storageBucket: 'your-project-id.appspot.com',
  );
}
